//! The published JSON Schemas: regenerated byte for byte, and every package
//! and expression fixture valid against them.
//!
//! `AXIOVAL_BLESS=1 cargo test -p axioval-ir --features schema --test
//! json_schema` rewrites the published copies.
#![cfg(feature = "schema")]
#![allow(missing_docs)]
use axioval_ir::schema;
use serde_json::{Value, json};
use std::path::{Path, PathBuf};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn published(file: &str) -> PathBuf {
    root().join("docs/src/schema").join(file)
}

fn read(path: &Path) -> Value {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("{}: {error}", path.display()))
}

fn validator(schema: &Value) -> jsonschema::Validator {
    jsonschema::draft202012::new(schema).expect("the generated schema is a valid 2020-12 schema")
}

fn assert_valid(validator: &jsonschema::Validator, name: &str, instance: &Value) {
    let errors: Vec<String> = validator
        .iter_errors(instance)
        .map(|error| format!("{} at {}", error, error.instance_path()))
        .collect();
    assert!(
        errors.is_empty(),
        "{name} is invalid:\n{}",
        errors.join("\n")
    );
}

/// The ruleset schema rooted at one of its definitions.
fn definition(name: &str) -> Value {
    let mut schema = schema::ruleset();
    let root = schema.as_object_mut().unwrap();
    for keyword in [
        "type",
        "properties",
        "required",
        "additionalProperties",
        "title",
    ] {
        root.remove(keyword);
    }
    root.insert("$ref".into(), format!("#/$defs/{name}").into());
    schema
}

#[test]
fn published_schemas_are_regenerated() {
    let bless = std::env::var_os("AXIOVAL_BLESS").is_some_and(|value| value == "1");
    for (file, schema) in [
        (schema::DEFINITIONS_FILE, schema::definitions()),
        (schema::RULESET_FILE, schema::ruleset()),
    ] {
        let expected = schema::to_pretty_json(&schema);
        let path = published(file);
        if bless {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &expected).unwrap();
        }
        let actual = std::fs::read_to_string(&path).unwrap_or_default();
        assert!(
            actual == expected,
            "{} is stale; regenerate it with AXIOVAL_BLESS=1 cargo test -p axioval-ir \
             --features schema --test json_schema",
            path.display()
        );
    }
}

#[test]
fn schemas_are_versioned_with_the_crate() {
    for schema in [schema::definitions(), schema::ruleset()] {
        assert!(
            schema["$id"]
                .as_str()
                .unwrap()
                .starts_with(schema::BASE_URL)
        );
        assert!(
            schema["$comment"]
                .as_str()
                .unwrap()
                .contains(&format!("axioval-ir {}", env!("CARGO_PKG_VERSION")))
        );
    }
}

#[test]
fn package_fixtures_are_valid() {
    let definitions = validator(&schema::definitions());
    let ruleset = validator(&schema::ruleset());
    // The canonical schema fixtures and the not-evaluated inventory packages.
    for directory in ["fixtures/schema-v0.1.0", "scripts/inventory"] {
        for (file, validator) in [
            ("definitions.json", &definitions),
            ("ruleset.json", &ruleset),
        ] {
            let path = root().join(directory).join(file);
            assert_valid(validator, &path.display().to_string(), &read(&path));
        }
    }
}

#[test]
fn expression_fixtures_are_valid() {
    let expression = validator(&definition("Expression"));
    let directory = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/expression");
    let mut count = 0;
    for entry in std::fs::read_dir(&directory).unwrap() {
        let path = entry.unwrap().path();
        if path
            .extension()
            .is_some_and(|extension| extension == "json")
        {
            assert_valid(&expression, &path.display().to_string(), &read(&path));
            count += 1;
        }
    }
    assert!(
        count > 0,
        "no expression fixtures in {}",
        directory.display()
    );
}

#[test]
fn values_written_by_the_types_are_valid() {
    // What the types serialize must validate too, the wire-only defaults
    // and skipped fields included.
    let ruleset: axioval_ir::RuleSetPackage =
        serde_json::from_value(read(&root().join("fixtures/schema-v0.1.0/ruleset.json"))).unwrap();
    assert_valid(
        &validator(&schema::ruleset()),
        "the serialized ruleset fixture",
        &serde_json::to_value(&ruleset).unwrap(),
    );
}

#[test]
fn invalid_drafts_are_rejected() {
    let ruleset = validator(&schema::ruleset());
    let fixture = read(&root().join("fixtures/schema-v0.1.0/ruleset.json"));

    let mut missing_root = fixture.clone();
    missing_root.as_object_mut().unwrap().remove("root");
    assert!(!ruleset.is_valid(&missing_root), "a ruleset needs a root");

    let mut unknown_field = fixture.clone();
    unknown_field["root"]["colour"] = json!("red");
    assert!(
        !ruleset.is_valid(&unknown_field),
        "unknown fields are refused"
    );

    let expression = validator(&definition("Expression"));
    let compare = |left: Value| {
        json!({
            "kind": "compare",
            "operator": "lessThan",
            "left": left,
            "right": {"kind": "literal", "value": {"type": "number", "value": 1.0}}
        })
    };
    assert!(expression.is_valid(&compare(json!({"kind": "parameter", "name": "limit"}))));
    for (why, draft) in [
        (
            "an unknown expression kind",
            compare(json!({"kind": "loop", "body": {"kind": "null"}})),
        ),
        (
            "a missing required field",
            json!({"kind": "compare", "operator": "lessThan", "left": {"kind": "null"}}),
        ),
        (
            "an unknown comparison",
            compare(json!({"kind": "null"}))
                .as_object()
                .map_or(Value::Null, |node| {
                    let mut node = node.clone();
                    node.insert("operator".into(), json!("approximately"));
                    Value::Object(node)
                }),
        ),
        (
            "a literal of a list kind",
            json!({"kind": "literal", "value": {"type": "stringList", "value": ["a"]}}),
        ),
        (
            "a date-time without an offset",
            json!({"kind": "literal", "value": {"type": "dateTime", "value": "2026-09-27T10:00:00"}}),
        ),
        (
            "an unknown field on a node",
            json!({"kind": "null", "colour": "red"}),
        ),
    ] {
        assert!(!expression.is_valid(&draft), "{why} is accepted: {draft}");
    }

    let selector = validator(&definition("Selector"));
    assert!(selector.is_valid(&json!({"kind": "all"})));
    assert!(
        !selector.is_valid(&json!({"kind": "objects", "objects": []})),
        "the host-only objects selector is never part of a package"
    );
}
